# Cache node_modules to cut down on build times.
cache:
  paths:
  - node_modules

stages:
  - frontend-test
  - backend-test

# Template for frontend CI tasks.
.frontend-template: &frontend-test
  variables:
    NPM_CONFIG_LOG_LEVEL: warn
    NODE_ENV: test
  before_script:
    - cd frontend
    - npm install
  image: node:6
  stage: frontend-test

# Template for backend CI tasks.
.backend-template: &backend-test
  image: java:8
  stage: backend-test
  before_script:
    - cd backend

# Check frontend for style issues.
frontend-lint:
  <<: *frontend-test
  script:
    - npm run lint

# Check backend for sanity.
backend-spec:
  <<: *backend-test
  script:
    - ./gradlew build
    - ./gradlew test
